service: graphql-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  timeout: 60

functions:
  api:
    handler: graphql.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline